---
title:    "Virginia Clean Energy Project"
subtitle: "Extract, transform and load datasets via the U.S. Energy Information Administration's API"
author:   Arthur Small
date:     "Version of `r Sys.Date()`"
output: html_notebook
---

This notebook includes code for retrieving and parsing datasets from the [application programming interface (API)](https://www.eia.gov/opendata/qb.php) maintained by the [Energy Information Administration](https://www.eia.gov) of the U.S. Department of Energy.


```{r load packages - install if needed}
if(!("jsonlite" %in% installed.packages()))  install.packages("jsonlite")
if(!("eia" %in% installed.packages()))       install.packages("eia")
if(!("RPostgres" %in% installed.packages())) install.packages("RPostgres")

library(here)
# library(readr)
library(tidyverse)
library(stringr)
library(jsonlite)
```


```{r initialize your personal EIA API key -- EDIT ME}
# Each user of the EIA API must obtain a personal API key.
# If you don't already have an API key, obtain one at: https://www.eia.gov/opendata/register.php

# Once you have your personal API key, edit and uncomment the line below:
my_api_key <- '0381054750e46296b0d7b98a91447166'

# Alternatively you may include this line in a separate file, and call it here. E.g.:
#source(here("etl","my_eia_api_key.R"))
```


```{r define function to fetch and parse a single EIA data series}
fetch_eia_series <- function(series_id){
  require(eia)
  
  eia_set_key(my_api_key) # set API key if not already set globally
  
  data_series <- eia_series(series_id)
  
  return(data_series)
}

```

```{r alternative function to retrieve and parse a single EIA data series}
get_EIA_series <- function(eiaKey,series_id) {
  require(jsonlite)
  require(data.table)
  # This function retrieves one EIA time-series with metadata
  # The function returns a list of parts of the series:
  #     seriesID,name,units,frequency,data (as data table)
  
  # eiaKey is your EIA API key
  eiaBase = paste0("http://api.eia.gov/series/?api_key=",eiaKey,"&series_id=") 
  
  vv = paste0(eiaBase,series_id)
  temp = readLines(vv, warn = "F")
  rd <- fromJSON(temp)
  print(paste0("Retrieving: ",rd$series$series_id))
  print(paste0(rd$series$name))
  
  # Now take the 'data' element from the list and make a data frame
  rd2 = data.frame(rd$series$data,stringsAsFactors = F)
  rd2 = data.table(rd2)
  
  setnames(rd2,1,"date"); setnames(rd2,2,'value')
  rd2[,value:=as.numeric(value)]
  rd2$date = as.Date(gsub('(\\d{4})(\\d{2})', '\\1-\\2-01', rd2$date))
  returnList = list(
    series_id = rd$series$series_id,
    name = rd$series$name,
    units = rd$series$units,
    frequency = rd$series$f,
    data = rd2
  )
  return(returnList) 
}

## Example code to call this function
#   eia_api_key = "0E59CFF12754E0513DEB30FB4850B0FA"
## Retrieve total distributed pv generation for Virginia
#   small_solar_series = get_EIA_series(eia_api_key,"ELEC.GEN.DPV-VA-99.M")
#   small_solar = small_solar_series$data  # <-- Extract just the data from the list
#   setnames(small_solar,2,"small_solar")
#   small_solar_series$name



```

```{r fetch a data series}
#library(here)
#here('eia_keys')

# Read in series IDs
#list_of_series_ids <- read.delim(here,'eia_keys')


  

# Fetch different data series
series_id1  <- "ELEC.GEN.ALL-VA-99.M"
series_id2 <- 'EMISS.CO2-TOTV-EC-TO-VA.A'
series_id3 <- 'SEDS.TETCB.VA.A'
series_id4 <- 'SEDS.TEPRB.VA.A'
series_id5 <- 'ELEC.SALES.VA-ALL.A'
series_id6 <- 'ELEC.GEN.ALL-VA-99.A'

series1 <- fetch_eia_series(series_id1)
series2 <- fetch_eia_series(series_id2)
series3 <- fetch_eia_series(series_id3)
series4 <- fetch_eia_series(series_id4)
series5 <- fetch_eia_series(series_id5)
series6 <- fetch_eia_series(series_id6)

# Display data
displaydata <- function(series) {
(series$data[[1]] -> series_data_tbl)
 return(series_data_tbl)
}

series_data_tbl1 <- displaydata(series1)
series_data_tbl2 <- displaydata(series2)
series_data_tbl3 <- displaydata(series3)
series_data_tbl4 <- displaydata(series4)
series_data_tbl5 <- displaydata(series5)
series_data_tbl6 <- displaydata(series6)


unnest(series1, cols = data) 
unnest(series2, cols = data) 
unnest(series3, cols = data) 
unnest(series4, cols = data) 
unnest(series5, cols = data) 
unnest(series6, cols = data) 

```




```{r}

str(get_EIA_series(my_api_key,series_id1)$data)
str(get_EIA_series(my_api_key,series_id2)$data)
str(get_EIA_series(my_api_key,series_id3)$data)
str(get_EIA_series(my_api_key,series_id4)$data)
str(get_EIA_series(my_api_key,series_id5)$data)
str(get_EIA_series(my_api_key,series_id6)$data)

```


```{r plot series}
library(ggplot2)
library(tidyr)

series_data_tbl1 %>% filter(year == 2019) %>%
  ggplot(aes(month, value)) + geom_line() + labs(y = series$units, title = series$name)

```

# Connect to PostgreSQL database

```{r open connection to PostgreSQL database}
# NOTE: To open a connection to the DB, you must first connect to the "UVA Anywhere" network.
# If you are not on UVA Grounds, you must connect to the "UVA Anywhere" network via VPN.
# For instructions on UVA's VPN services, see:
# https://virginia.service-now.com/its?id=itsweb_kb_article&sys_id=f24e5cdfdb3acb804f32fb671d9619d0

# STORING PERSONAL ACCESS CREDENTIALS TO THE DATABASE:
# Opening a connection to the DB requires credentials, including your personal password, that you should 
# *not* incorporate into code, especially code that will be shared.
# Instead, store your credentials in a file on your local drive.
# Structure this file as follows:
    # # Network: "UVA Anywhere"
    # dbname   <- "postgres"
    # host     <- "eo43.postgres.database.azure.com"
    # port     <- 5432
    # user     <- "YOUR-USER-NAME"
    # password <- "YOUR-PASSWORD"
# Here, the file is named "my_postgres_db_credentials.R", and is stored in the "etl" subfolder of the main
# project directory. The project .gitignore file includes a line "my_*.R"; this tells git to not synch
# this and similar files with personal credentials.
# There are safer, more formal ways to secure credentials, but this method should be good enough for our
# purposes, given that the data we are storing are not sensitive.

source(here("etl", "jackson_postgres_login.R"))

# create a connection to the postgres database
# note that "con" will be used later in each connection to the database
# library(RPostgres)
# library(DBI)
# drv <- RPostgres::Postgres()

require("RPostgreSQL")
drv <- dbDriver("PostgreSQL")

con <- dbConnect(drv, dbname = dbname, host = host, port = port, user = user, password = password)

rm(password) # removes the password from program memory

# check the connection
dbExistsTable(con, "fuel")
# TRUE
dbListTables(con)
```


```{r load series to PostgreSQL database}
# Convert series_id to a postgres-acceptable table name
library(stringr)

get_name <- function(series_id) {
  db_table_name <- str_to_lower(paste("eia", str_replace_all(series_id, "[.-]", "_"), sep="_"))
  return(db_table_name)
}

db_table_name1 <- get_name(series_id1)
db_table_name2 <- get_name(series_id2)
db_table_name3 <- get_name(series_id3)
db_table_name4 <- get_name(series_id4)
db_table_name5 <- get_name(series_id5)
db_table_name6 <- get_name(series_id6)


#db_table_name1 <- str_to_lower(paste("eia", str_replace_all(series_id1, "[.-]", "_"), sep="_"))

# write data series to the PostgreSQL database "postgres": OVERWRITES EXISTING TABLE!
dbWriteTable(con, db_table_name1, value = series_data_tbl1, append = FALSE, overwrite = TRUE, row.names = FALSE)
dbWriteTable(con, db_table_name2, value = series_data_tbl2, append = FALSE, overwrite = TRUE, row.names = FALSE)
dbWriteTable(con, db_table_name3, value = series_data_tbl3, append = FALSE, overwrite = TRUE, row.names = FALSE)
dbWriteTable(con, db_table_name4, value = series_data_tbl4, append = FALSE, overwrite = TRUE, row.names = FALSE)
dbWriteTable(con, db_table_name5, value = series_data_tbl5, append = FALSE, overwrite = TRUE, row.names = FALSE)
dbWriteTable(con, db_table_name6, value = series_data_tbl6, append = FALSE, overwrite = TRUE, row.names = FALSE)

# query the data from postgreSQL 
dbGetQuery(con, paste("SELECT * from", db_table_name)) %>% as_tibble() -> df_postgres 

# compare the two data.frames
identical(series_data_tbl, df_postgres)

# Create basic graph of the Data
# require(ggplot2)
# ggplot(df_postgres, aes(x = as.factor(cyl), y = mpg, fill = as.factor(cyl))) +
#   geom_boxplot() + theme_bw()

```

# Close connection

```{r close db connection}
dbDisconnect(con)
dbUnloadDriver(drv)
```


```{r retrieve updated manifest file to get info on latest updates,eval=FALSE}
## [IGNORE THIS CODE]
#
# library(httr)
# url <- "http://api.eia.gov/bulk/manifest.txt"
# 
# manifest <- stream_in(file(url))
# 
# str(manifest)
# 
# # flatten(manifest)
# 
# t(manifest$dataset[[2]])
```


